image: woowe/project-tracker:latest

stages:
  - test
  - deploy

# cache:
#   paths:
#     - node_modules/

build_then_deploy_staging:
  stage: test
  environment: Test
  only:
    - /^issue-.*$/
  script:
    - npm install
    - ng build -prod -e dev
    - firebase use --token 1/-4muSidhlj-PElnBmWc254UusUuvxqNpWPqHsAMQUik project-tracker-staging
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token 1/-4muSidhlj-PElnBmWc254UusUuvxqNpWPqHsAMQUik


deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install
    - ng build -prod -e prod
    - firebase use --token 1/-4muSidhlj-PElnBmWc254UusUuvxqNpWPqHsAMQUik project-tracker-c98a9
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token 1/-4muSidhlj-PElnBmWc254UusUuvxqNpWPqHsAMQUik